wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1647963583
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.5
      5: 0.12.9
      8:
      - 3
      - 5
beta:
  desc: null
  value: 1
dataset:
  desc: null
  value: mnist
gamma:
  desc: null
  value: 0.001
load_trained_model:
  desc: null
  value: true
meta_batch_size:
  desc: null
  value: 8
meta_lr:
  desc: null
  value: 0.003
mnist_pixels_to_permute_test:
  desc: null
  value: 100
mnist_pixels_to_permute_train:
  desc: null
  value: 1000
n_epochs:
  desc: null
  value: 100
n_shots:
  desc: null
  value: 1
n_test_epochs:
  desc: null
  value: 2
n_ways:
  desc: null
  value: 5
per_task_lr:
  desc: null
  value: 0.1
reset_clf_on_meta:
  desc: null
  value: false
seed:
  desc: null
  value: 42
test_adapt_steps:
  desc: null
  value: 1
train_adapt_steps:
  desc: null
  value: 5
train_sample_size:
  desc: null
  value: 10
